@Host = https://localhost
@Port = 7250
@Users.API_HostAddress = {{Host}}:{{Port}}
@ApiKey = cCgO8K8UmiwBS7g3Ljw

###

GET {{Users.API_HostAddress}}/api/Users/
X-API-KEY: {{ApiKey}}

###

GET {{Users.API_HostAddress}}/api/Users/2
X-API-KEY: {{ApiKey}}

###

POST {{Users.API_HostAddress}}/api/Users/
X-API-KEY: {{ApiKey}}
Content-Type: application/json
{
  "userName": "MikroCop2",
  "fullName": "MikroCop2",
  "email": "MikroCop@gmail.com",
  "mobile": "/",
  "language": "English",
  "culture": "Christian",
  "password": "User"
}

###

DELETE {{Users.API_HostAddress}}/api/Users/4
X-API-KEY: {{ApiKey}}

###

PATCH {{Users.API_HostAddress}}/api/Users/2
X-API-KEY: {{ApiKey}}
Content-Type: application/json
{
  "fullName": "Luka Lah",
  "email": "luka11.lah@gmail.com",
  "mobile": "+38640570989",
  "culture": "Christian",
  "password": "luka123"
}

###

POST {{Users.API_HostAddress}}/api/Users/validate-credentials/
X-API-KEY: {{ApiKey}}
Content-Type: application/json
{
  "email": "luka11.lah@gmail.com",
  "password": "luka123"
}
