@Host = https://localhost
@Port = 7250

@Users.API_HostAddress = {{Host}}:{{Port}}

GET {{Users.API_HostAddress}}/weatherforecast/
Accept: application/json
ProjectURL: {{$projectUrl}}
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}}
Random-int: {{$randomInt}}

###

GET {{Users.API_HostAddress}}

###

POST {{Users.API_HostAddress}}/weatherforecast/generate?count=-3
Content-Type: application/json
{
  "Min": -23,
  "Max": 23
}