@Host = https://localhost
@Port = 7250

@Users.API_HostAddress = {{Host}}:{{Port}}

GET {{Users.API_HostAddress}}/api/Users/

###

GET {{Users.API_HostAddress}}/api/Users/4

###

POST {{Users.API_HostAddress}}/api/Users/
Content-Type: application/json
{
  "userName": "MikroCop2",
  "fullName": "MikroCop2",
  "email": "MikroCop@gmail.com",
  "mobile": "/",
  "language": "English",
  "culture": "Christian",
  "password": "User"
}
###

DELETE {{Users.API_HostAddress}}/api/Users/4

###

PATCH {{Users.API_HostAddress}}/api/Users/2
Content-Type: application/json
{

  "fullName": "Luka Lah",
  "email": "luka11.lah@gmail.com",
  "mobile": "+38640570989",
  "culture": "Christian",
  "password": "luka123"
}